CODE 		SEGMENT            			;H8255-2.ASM
ASSUME 	CS:CODE
IOCONPT EQU 0FF2BH			;8255控制口
IOAPT	 EQU 0FF28H			;PA口
IOBPT	 EQU 0FF29H			;PB口
IOCPT	 EQU 0FF2AH			;PC口
	ORG 11e0H

START:		
    MOV AL,82H						;PB输入,PA,PC输出
	MOV DX,IOCONPT
	OUT DX,AL		
				;写命令字
	MOV DX,IOBPT					;读PB口
	IN AL,DX
	MOV BYTE PTR DS:[0601H],AL	;保存PB口数据
	
MOV DX,IOCONPT				;8255控制口
	MOV AL,80H
	OUT DX,AL						;写命令字, PA,PB,PC输出
	MOV DX,IOBPT					;
	MOV AL,DS:[0601H]
	OR AL,0F0H
	OUT DX,AL
	MOV DX,IOCPT
	MOV AL,0F0H					
	OUT DX,AL						;四路口红灯全亮
	CALL DELAY1					;延时
IOLED0:   	MOV AL,10100101B
	MOV DX,IOCPT
	OUT DX,AL						;南北绿灯亮,东西红灯亮
	CALL DELAY1					;延时
	CALL DELAY1					;延时
	OR AL,0F0H
	OUT DX,AL						;南北绿灯灭
	MOV CX,8H
  
IOLED1:   	MOV DX,IOBPT
	MOV AL,DS:[0601H]
	AND AL,10101111B				
	OUT DX,AL						;南北黄灯亮
	CALL DELAY2					;延时
	OR AL,01010000B				
	OUT DX,AL						;南北黄灯灭
	CALL DELAY2					;延时
	LOOP IOLED1					;南北黄灯闪烁8次
	；MOV DX,IOCPT
	；MOV AL,0F0H
	；OUT DX,AL						;四路口红灯全亮
	；CALL DELAY2					;延时
	MOV AL,01011010B				
	OUT DX,AL						;东西绿灯亮
	CALL DELAY1					;延时
	CALL DELAY1
	OR AL,0F0H
	OUT DX,AL						;东西绿灯灭
	MOV CX,8H
IOLED2:   	MOV DX,IOBPT
	MOV AL,DS:[0601H]
	AND AL,01011111B
	OUT DX,AL						;东西黄灯亮
	CALL DELAY2					;延时
	OR AL,10100000B
	OUT DX,AL						;东西黄灯灭
	CALL DELAY2					;延时
	LOOP IOLED2					;东西黄灯闪烁8次
	MOV DX,IOCPT
	MOV AL,0F0H
	OUT DX,AL						;四路口红灯全亮
	CALL DELAY2
	JMP IOLED0						;循环继续
DELAY1:   	PUSH AX
	PUSH CX
	MOV CX,0030H
DELY2:  	CALL DELAY2
	LOOP DELY2
	POP CX
	POP AX
	RET
DELAY2:   	PUSH CX
	MOV CX,8000H
DELA1: 	LOOP DELA1
	POP CX
	RET
CODE ENDS
END  START
